### ISSUE TITLE
Badges should only reflect upstream master 

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#25]
Currently the badges show failed status when other users submit prs that fail

**Comment by Rabadash8820** [comment]
From looking at the [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository): `Status badges show whether a workflow is currently failing or passing`. The badge doesn't care whether the workflow passed/failed due to a PR, push, or whatever, it just shows the latest result. So I think you want to use the [Example using the `branch` parameter](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#example-using-the-branch-parameter). Here is what that badge would show if you use `master` (currently passing) vs `return-license-fix` (the last PR branch that failed):

`[![Actions status](https://github.com/webbertakken/unity-builder/workflows/Actions%20%F0%9F%98%8E/badge.svg?branch=master)](https://github.com/webbertakken/unity-builder/actions?query=branch%3Amaster+workflow%3A%22Actions+%F0%9F%98%8E%22)`

[![Actions status](https://github.com/webbertakken/unity-builder/workflows/Actions%20%F0%9F%98%8E/badge.svg?branch=master)](https://github.com/webbertakken/unity-builder/actions?query=branch%3Amaster+workflow%3A%22Actions+%F0%9F%98%8E%22)

`[![Actions status](https://github.com/webbertakken/unity-builder/workflows/Actions%20%F0%9F%98%8E/badge.svg?branch=return-license-fix)](https://github.com/webbertakken/unity-builder/actions?query=branch%3Amaster+workflow%3A%22Actions+%F0%9F%98%8E%22)`

[![Actions status](https://github.com/webbertakken/unity-builder/workflows/Actions%20%F0%9F%98%8E/badge.svg?branch=return-license-fix)](https://github.com/webbertakken/unity-builder/actions?query=branch%3Amaster+workflow%3A%22Actions+%F0%9F%98%8E%22)

**Comment by Rabadash8820** [comment]
Ok so actually I think you're fine and can probably close this Issue. Take a look at that PR that I just opened (#28).

**Comment by webbertakken** [comment]
Mostly it seems fine, however as you correctly pointed out;

> So why did the badge of the Builder repo turn red after the check for webbertakken/unity-builder#14 failed? Well, I think that was because I opened a PR from the master branch of my fork, so presumably GitHub Action's badge system can't distinguish master in a fork from master in the base repo.

So that's either a bug in github actions or we have to find a way that also works for PRs from the master branch of forks.
