### ISSUE TITLE
Workflow should correctly run for external PRs

### ISSUE THREAD

**Issue by webbertakken** [webbertakken/unity-actions#27]
Currently PRs from forks seem to always fail because the up-to-date code seems to not run and it is unclear which repos variables are being used.

**Comment by Rabadash8820** [comment]
So after doing some research, I think these are the facts that will help you test an Action in response to a PR:

- When someone creates a fork and then opens a PR, the PR is actually opened in the *upstream* (your) repo, and the `pull_request` GitHub event is raised there as well. [source](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-events-for-forked-repositories)
- That `pull_request` event then triggers any workflows with `on: pull_request` that are defined *in that commit*. I.e., any changes to a workflow config in that PR will take effect, and any workflows with `on: pull_request` that were *added* by the PR will also be run. This is all based on my own experience while creating workflows in a PR when I was first trying to add your Unity Actions.
- Because the workflows run in *your* repo, not the fork, they use *your* secret values (and rack up *your* Actions usage for billing). Actions aren't even enabled in the fork by default (see this screenshot of the Actions tab in my fork):

![image](https://user-images.githubusercontent.com/8388785/72241252-597d7100-35b4-11ea-9087-5b8eaa55552c.png)

- While the PR's updated workflow config is used, that config is probably pointing at the latest *published* version of your Actions, meaning the "old" Actions are being run, not the new ones that would be created by the PR. Our experience with the last couple PRs in the `unity-builder` repo is proof of that.
- To run the Action as it is inside the PR, you would need to tweak the `jobs.<job_id>.steps.uses` config to point at the PR's latest commit SHA, rather than the version published in the GitHub marketplace. [source](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsuses)
- To access the PR's latest commit SHA inside the workflow config, you should be able to use the [`github` context](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context) object (note that I haven't tested this). So you're updated config might look something like:

```yml
name: Actions 😎
on:
  pull_request: {}
  push: { branches: [master] }
env: {}   # UNITY_STUFF
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Builder
        uses: ${{ github.repository }}@${{ github.sha }}  # webbertakken/unity-builder@123abc
        with: {}   # Unity stuff
      # etc. 
```

- This config would no longer be copy-pasteable by your users, since obviously we _do_ want the latest published version. In which case, you'll probably need to make a separate example workflow config, or else just keep your documentation thorough.

**Comment by Rabadash8820** [comment]
Based on the above, I or you or someone else should be able to open a PR to test the updated workflow config above. But remember that the workflow that runs in response to that PR will be using *your* secret values.

**Comment by Jibbajabbafic** [comment]
We could setup a separate workflow for PRs which uses this method, and then keep the original one so users can still copy paste it.

**Comment by webbertakken** [comment]
> Based on the above, I or @webbertakken or someone else should be able to open a PR to test the updated workflow config that I presented, or something similar. But remember that the workflow that runs in response to that PR will be using the _base repo's_ secret values.

@Rabadash8820 great research! 👌 Thanks a lot for that list of facts. I think it might be a good start to just use github context for this as you suggest since the action runs on the upstream. Would you create a PR with proof of concept for this? If it works, we can simply merge it and apply the same to all related actions too and close this issue, to stay a bit light weight. 

> While the PR's updated workflow config is used, that config is probably pointing at the latest published version of your Actions, meaning the "old" Actions are being run, not the new ones that would be created by the PR. Our experience with the last couple PRs in the unity-builder repo is proof of that.

If the actions runs in context of the PR, and the PR references a relative path, I still find it strange that this relative path is related to the latest published version. That might be a bug in GitHub Actions tbh.

**Comment by Rabadash8820** [comment]
> If the actions runs in context of the PR, and the PR references a relative path, I still find it strange that this relative path is related to the latest published version.

Well I guess its because the relative paths in use are actually the ones in the published version, not the PR. I assume you're talking about things like the path to the `Dockerfile` in `action.yml`, and the path to `entrypoint.sh` in the `Dockerfile`. If everything starts with the `action.yml` *in the published version*, then I could see how all other path lookups would be relative to the published version's files, not the PR's. But I agree, GitHub should really document a more canonical way of testing Actions with a workflow in that Action's repo...

>Would you create a PR with proof of concept for this?

Yeah I'll get around to it 🙃

**Comment by webbertakken** [comment]
> Well I guess its because the relative paths in use are actually the ones in the published version, not the PR. I assume you're talking about things like the path to the Dockerfile in action.yml, and the path to entrypoint.sh in the Dockerfile.

Actually I meant the workflow in builder which has this problem but references a relative path to the action of the PR. See `./` in main.yml

![SmartSelect_20200113-212518_Chrome](https://user-images.githubusercontent.com/20756439/72289699-f0e1d300-364b-11ea-9c40-913997b0993e.jpg)

I find it odd that this references the latest published version.

> Yeah I'll get around to it upside_down_face

Awesome! Thanks a lot. I think you're the best to do it given that you have detailed context for this one.

**Comment by Rabadash8820** [comment]
> Actually I meant the workflow in builder which has this problem but references a relative path to the action of the PR.

Oh I didn't even see that. I think you're right actually. According to the [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#example-using-action-in-the-same-repository-as-the-workflow), it looks like you can reference an action stored at a relative path in the same directory. My testing so far in webbertakken/unity-builder#16 suggests that this DOES work (see over there for more info). So as far as I can tell, as long as you `uses` the repo root (`./`), this Issue should be solved.

**Comment by webbertakken** [comment]
Your last comment is not in line with what you said earlier.

> While the PR's updated workflow config is used, that config is probably pointing at the latest published version of your Actions, meaning the "old" Actions are being run, not the new ones that would be created by the PR. Our experience with the last couple PRs in the unity-builder repo is proof of that.

I'll investigate it when I have time.

**Comment by Rabadash8820** [comment]
Correct, I was just speculating when I said it was "probably pointing at the latest published version", and I didn't realize that your `unity-builder` workflow `uses` a relative path rather than an actual `@version`.  Based on the check results of webbertakken/unity-builder#16, it looks like PRs in `unity-builder` are indeed using the code present in the PR, not the published version.

**Comment by webbertakken** [comment]
I'm confused. What about your [comment](https://github.com/webbertakken/unity-builder/pull/14#ISSUECOMMENT-573361230) in https://github.com/webbertakken/unity-builder/pull/14?

**Comment by Rabadash8820** [comment]
What about it? That PR was just for the changes that you had suggested in #26. If you're referring to when I said:

> I set `UNITY_EMAIL`, `UNITY_PASSWORD`, and `UNITY_SERIAL` in my fork so that the test builds would pass"

that was just a confused younger version of myself thinking that I needed to have secrets present in my fork to fix the PR checks. As I later learned and described above, the fork's secrets don't matter.

**Comment by Jibbajabbafic** [comment]
Posting this here for reference:

FYI this might be the issue:
```
With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository.
```
From: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets#using-encrypted-secrets-in-a-workflow

This means there's no way to pass secrets to any actions run on a PR since it would be trivial for anyone to open a malicious PR and leak the secret.

**Comment by Rabadash8820** [comment]
Nice catch @Jibbajabbafic! I bet that's the problem. This did otherwise seem like a pretty serious leak in Action security 😬

So I guess there's no way to guarantee that a check will pass for a PR from a fork. They might work if @webbertakken (or anyone with write access?) were to restart them, but idk.

**Comment by webbertakken** [comment]
@Rabadash8820 

> What about it? That PR was just for the changes that you had suggested in #26. If you're referring to when I said:
> 
> > I set `UNITY_EMAIL`, `UNITY_PASSWORD`, and `UNITY_SERIAL` in my fork so that the test builds would pass"
> 
> that was just a confused younger version of myself thinking that I needed to have secrets present in my fork to fix the PR checks. As I later learned and described above, the fork's secrets don't matter.

Please note that your analysis are sometimes not accurate. Actually in the comment I mentioned above you show that your changes are not showing up, as the docker run should show `--ENV UNITY_EMAIL --ENV UNITY_PASSWORD --ENV UNITY_SERIAL` as part of the command line.

It's ok to still be learning or be in over your head as you stated. Just don't make assumptions and state them as facts, as they can be quite misleading.

So the reason why your tests failed when changing any of the js files was always because you didn't use the pre-commit hook and as such the dist files are never created. See my [comment](https://github.com/webbertakken/unity-builder/pull/18#issuecomment-575054683) your latest PR for more info on how to go about it.

Some tests may need to be re-verified. I'm guessing that this (no commit hook ran) may actually be the sole cause for workflow "not running correctly".

I'll create a test that checks if builder.js is up-to-date and make the pre commit hook fail if node modules are not installed.

Good job on helping verify the issue!

**Comment by Rabadash8820** [comment]
@webbertakken Sorry for the confusion! I got the impression that you were still figuring out some of these workflow/action issues yourself, so I was just trying to share what sources I had found as I went. Anyway, I'll try to get a correct build working on my end. It would be good to add some kind of "contributing" docs so future contributors don't run into similar issues.

**Comment by Jibbajabbafic** [comment]
I think we can work around this for personal licenses by simply including the license file unencrypted in the repo since those are generated specifically for the machines that run the GitHub Actions.

Correct me if I'm wrong but I don't think there's anything malicious that someone could do since it's just a personal license, and you could always make a new Unity account if you're worried about it being compromised.

**Comment by webbertakken** [comment]
That is definitely an option. And I agree not much could happen, however I generally consider it as bad practice to include secrets in code. So we'll do it if it's indeed the only option.

**Comment by Rabadash8820** [comment]
I think what you need is some way to filter your workflow so that it doesn't run for pull requests generated from a `master` branch. Unfortunately, the `on.pull_request.branches` and `on.pull_request.branches-ignore` filters match against the _target_ branch, not the source branch (see [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestbranchestags), `For a pull_request event, only branches and tags on the base are evaluated.`)

The only other option that I can find is to [set an `if` filter on every step](https://github.community/t5/GitHub-Actions/How-to-ignore-branch-names-on-pull-requests/td-p/35309). I.e., your workflow might look something like:

```yml
name: Actions 😎
on:
  pull_request: {}
  push: { branches: [master] }
# ...
jobs:
  buildForAllPlatforms:
    # ...
    steps:
      - uses: actions/checkout@v1
        if: github.head_ref != 'master'
      - uses: ./
        if: github.head_ref != 'master'
        #with:
      - uses: actions/upload-artifact@v1
        if: github.head_ref != 'master'
        #with:
```

Note, from the docs for [`github.head_ref`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions#github-context):

> This property is only available when the event that triggers a workflow run is a `pull_request`.

So idk if using `head_ref` would break the workflow when it runs in response to a `push`.
