### ISSUE TITLE
Having a no much file error during the run test/build

### ISSUE THREAD

**Issue by AlexouWolfy** [webbertakken/unity-actions#53]
Hi, when using the unity-action, I always receive this error
```
###########################
#    Edit Mode Results    #
###########################

cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/editmode-results.xml: No such file or directory

###########################
#    Play Mode Results    #
###########################

cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
cat: /github/workspace/artifacts/playmode-results.xml: No such file or directory
##[error]The process '/usr/bin/docker' failed with exit code 1
```
Even with files created, I still get the message, Need help please thanks

**Comment by webbertakken** [comment]
That message simply means that your tests never ran. 

You'll have to scroll up for the specific reason.

In case the reason is that it doesn't find any tests; Make sure you've followed Unity's official docs (or better youtube movies) about how to setup test assembly files.

Let me know if that worked. If not, make sure you provide some extra information about the specific reason as mentioned above.

**Comment by webbertakken** [comment]
@ItsAlexou Did you get any further with this?

**Comment by AlexouWolfy** [comment]
It's done now
