### ISSUE TITLE
Upload .ipa as Artifact (.apk when Android is supported)  

### ISSUE THREAD

**Issue by Smponias** [webbertakken/unity-actions#54]
Is there any possibility to upload an .ipa (or .apk when Android is supported) as artifact? 

This would be really cool!

**Comment by webbertakken** [comment]
Hi @Smponias,

Thanks for creating this issue! 

What have you researched about this issue so far? Note that I've never created an android build so far and don't have proper context about this.

**Comment by davidmfinol** [comment]
I think unity-actions requires a linux image, and I don't think it's possible to create an .ipa on anything other than macOS.

So my plan is to create a 2 job workflow:
1. Use unity-actions to generate the xcode project, and then upload the xcode project as an artifact.
2. Download the xcode project in a second job, which will use a [fastlane-action](https://github.com/marketplace/actions/fastlane-action) to build and upload the .ipa to the app store.

**Comment by webbertakken** [comment]
Would love to see the results of your experiment! Maybe it's something we can document or integrate, so everyone will be able to do it.

**Comment by davidmfinol** [comment]
I successfully created [a workflow which builds an .ipa and uploads it to the App Store](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/66276856/workflow).

I had to follow several different guides to get this working, and unfortunately, anyone who wants to have a similar workflow will need to do more than copy my code and edit the appropriate variables/secrets.

I'm thinking that when I have some time in the future, I may try writing a guide similar to [one of the guides I followed](https://medium.com/@mandarin_x/continuous-integration-for-unity-projects-using-travisci-5b25e691ab58).

In the meantime, I am of course happy to answer any questions about the process here.

**Comment by webbertakken** [comment]
That looks great! Good work.

A guide would be very helpful!

Also feel free to submit a PR for any changes to the default builder script in Unity Builder. We could add your customParameters as optional parameters (or even required for some build targets).

**Comment by davidmfinol** [comment]
The changes I made to the default builder script was for Android builds.
If I can get the Android builds working (hopefully after @GabLeRoux adds the NDK next week), I'll likely see if I can raise a PR for that.

-androidAppBundle would be a useful optional parameter for people who want to submit builds to the Google Play store.
I think -keystorePass and -keyaliasPass would probably be

**Comment by GabLeRoux** [comment]
@davidmfinol I just published them ;) here are the versions where ndk is available:  
https://gitlab.com/gableroux/unity3d/-/merge_requests/91

**Comment by webbertakken** [comment]
@davidmfinol would you still be up for sharing your approach? It would be very much appreciated!

**Comment by davidmfinol** [comment]
Sure, I should have some time this weekend. I'll post a link here when I've got it ready.

**Comment by davidmfinol** [comment]
Alright, I wrote this: https://medium.com/@davidmfinol/ci-cd-with-unity-github-actions-and-fastlane-e7aaa337784?source=friends_link&sk=b8d6c587f0e59d61c8a6ebf060a31cca
Feedback is welcome!

**Comment by webbertakken** [comment]
@davidmfinol great post! Thank you for writing that and making it public for everyone.

Regarding this section that you wrote:

> I am also using a custom build method Cgs.Editor.BuildCgs.BuildProject in order to be able to pass in the keystore passwords and to be able to create an Android app bundle .aab instead of a regular .apk. I’m hoping that in the future, this custom build method will be made unnecessary by being able to provide these parameters to the default Unity Builder build method.

Regarding this, the plan is definitely to incorporate more functionality in the default builder script! It's just that every iteration takes time and I'm doing all of it in my free time :) I'm sure someone will contribute it or otherwise I will add it in the future myself.

Also feel free to pass a PR with the changes that you need to make it available in [default build script](https://github.com/webbertakken/unity-builder/tree/master/action/default-build-script) in [Unity Builder](https://github.com/webbertakken/unity-builder). In the end the idea is to make CI/CD as accessible as possible, also for the newer developers under us.

Could you maybe also check if the automatic versioning that is introduced in [releases](https://github.com/webbertakken/unity-builder/releases) `v0.13` and `v0.14` would work for you?  It uses semantic versioning and is designed to work multi-platform.

**Comment by davidmfinol** [comment]
When I have some time again (maybe in another couple of weeks), I'll try and raise a PR to add those Android parameters to the default build script.

I also think automatic versioning is a great idea. It looks like your implementation requires using the default build script, so I'll wait until after I am able to use the default build script to try it out.

**Comment by webbertakken** [comment]
> When I have some time again (maybe in another couple of weeks), I'll try and raise a PR to add those Android parameters to the default build script.
> 
> I also think automatic versioning is a great idea. It looks like your implementation requires using the default build script, so I'll wait until after I am able to use the default build script to try it out.

Thank you for considering to raise a PR and glad you think automatic versioning is good idea!

Actually the version is generated in the bootstrapper. All the build script needs to do is assign the value of build parameter `-version` to `PlayerSettings.bundleVersion`, as can be seen in the main [script](https://github.com/webbertakken/unity-builder/blob/master/action/default-build-script/Assets/Editor/Builder.cs#L30).

**Comment by davidmfinol** [comment]
I tried it out:
I get [warnings in the logs](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/96301329), but it seems to generate a reasonable version number. 
It seems to append a patch number to whatever version is in the latest release tag, so I guess I'll start tagging my releases with just \<major\>.\<minor\> instead of \<major\>.\<minor\>.\<patch\>.

I do have another concern, though:
For each submission to the Mac App Store, `PlayerSettings.buildNumber.Standalone` needs to be incremented. Likewise, Google Play requires incrementing `PlayerSettings.AndroidBundleVersionCode`. These are both integers, so semantic versioning wouldn't apply. 
 I know UWP builds are not fully supported yet, but I also manually update `PlayerSettings.metroPackageVersion` for Microsoft Store submissions. This version number should match the `PlayerSettings.bundleVersion`, with an [extra .0 appended per Microsoft's requirements](https://docs.microsoft.com/en-us/windows/uwp/publish/package-version-numbering#version-numbering-for-windows10-packages).

Any thoughts on how to handle those? Updating the version number automatically doesn't really help if we still have to manually update these other version codes.

**Comment by webbertakken** [comment]
@davidmfinol Indeed, the idea is that the &lt;patch> level is automatic and no longer requires an explicit tag.

Actually according to this [blogpost](https://blog.redbluegames.com/version-numbering-for-games-in-unity-and-git-1d05fca83022) (directly under title _"How to Automate Semantic Versioning with Git"_) the one version number is automatically propagated to other version fields.

Now I have not tested this for all platforms, but I was hoping that if you leave the other fields empty it would do this automatically.

> Updating the version number automatically doesn't really help if we still have to manually update these other version codes.

If the above doesn't happen to be the case, we can always still derive an integer based on the version and setting these specific fields to these derived values. For example:

Semantic version `1.2.37` could become `1002037` (allowing 3 digits space for each section) for Android and iOS, whereas for windows it could just become `1.2.37.0` without any problem by the looks of it.

What do you think?

**Comment by davidmfinol** [comment]
> Actually according to this blogpost (directly under title "How to Automate Semantic Versioning with Git") the one version number is automatically propagated to other version fields.

The version number is shared for all platforms. 
These version codes are _additional_ numbers used internally by the different stores to determine which version to distribute to users who want to download the app from those stores. 

See both Version and Bundle Version Code in the Android Player Settings:
![AndroidPlayerSettings](https://user-images.githubusercontent.com/1088474/81111562-e7be8f80-8ee2-11ea-88e8-b2b3febd5992.png)

> Semantic version 1.2.37 could become 1002037 (allowing 3 digits space for each section) for Android and iOS, whereas for windows it could just become 1.2.37.0 without any problem by the looks of it.

I think this would work well!

**Comment by joshmmo** [comment]
I would suggest using fastlane for uploads.
https://fastlane.tools/

Once you have the apk or ipa for mobile it's very easy to configure fastlane to upload the file to the proper store.

**Comment by webbertakken** [comment]
> I would suggest using fastlane for uploads.
> https://fastlane.tools/
> 
> Once you have the apk or ipa for mobile it's very easy to configure fastlane to upload the file to the proper store.

@joshmmo I would be very interested in having some documentation in the form of some simple instructions on how to set this up in our new [docs](https://github.com/Unity-CI/Website) website. Would you be willing to write the initial markdown in this (see the docs folder)?

Essentially the idea is to have 1 page per platform or tool, and to describe how you use it as a followup step after unity-actions or your own custom setup using unity3d ci.

**Comment by webbertakken** [comment]
These version numbers and extensions should now work, as far as builders responsibility goes.

Indeed https://fastlane.tools/ is a good way to go for mobile builds, as a next step following unity-builder.
