### ISSUE TITLE
Error when running builder on release tag publish

### ISSUE THREAD

**Issue by davidmfinol** [webbertakken/unity-actions#67]
**Describe the bug**
I have configured my workflow to run when I publish a new release tag, but I get error "##[error]The process '/usr/bin/git' failed with exit code 128" when it runs on that trigger.

**To Reproduce**
- Create tag "v1.27" with [this workflow](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/102560141/workflow).

**Expected behavior**
- Set version as 1.27.0 and successfully run the workflow.

**Screenshot**
I'd like to highlight line 5 of the workflow:
![workflow](https://user-images.githubusercontent.com/1088474/81709169-534eb280-9437-11ea-828f-8f80c87d16ea.png)

Also, I don't see "[new tag]  v1.27" in the [output logs](https://github.com/finol-digital/Card-Game-Simulator/actions/runs/102560141).

**Additional context**
I don't get any errors on push to develop or master, so it seems to me that the problem is with generating the version number when the trigger is publishing the release tag.
Can we add in some logic to support this scenario?

**Comment by davidmfinol** [comment]
I was planning to try raising the PR for the Android build parameters this weekend, but this issue is a bigger priority for me. 
@webbertakken If you're busy, maybe I can try looking into this issue instead this weekend?

**Comment by webbertakken** [comment]
@davidmfinol Aha. Looks like it doesn't parse the `git describe` command properly. A bit annoying that it doesn't even give any output. This does however have everything to do with the automated build versioning that i introduced in the last 3 versions.

A temporary workaround could be to make a commit for the tag, and tag that commit, then `push --tags`, and run the pipeline for the commit instead of the tag.

And yes, of course feel free to help out in the way that you feel most comfortable.

**Comment by webbertakken** [comment]
@davidmfinol please note I have a refactor in the pipeline for Input, BuildArguments which also hits versioning a tiny bit, so you'll have to rebase. There should be no real conflicts though.

I think we can just apply your suggestion from [here](https://github.com/davidmfinol/unity-builder/commit/733e540ae8301c5e4a170493544787348a366a65#commitcomment-39245781)

> @webbertakken Thanks for the info.
> 
> I've run out of time to work on it this weekend, but I did confirm that the reason I was getting the error was due to `origin/${this.branch}` being invalid on `tag`. Specifically, GITHUB_REF takes the format [refs/tags/{tag}](https://github.com/finol-digital/Card-Game-Simulator/runs/684135379?check_suite_focus=true#step:6:71) instead of `refs/heads/{branchName}`.
> 
> I'm thinking the solution may be something as simple as this:
> 
> ```
>   static async getVersionDescription() {
>     const tag = await this.getTag();
>     const head =  tag ? 'HEAD' : `origin/${this.branch}`;
>     return System.run('git', [
>       'describe',
>       '--long',
>       '--tags',
>       '--always',
>       head,
>     ]);
>   }
> ```
> 
> I think `getTag()` should obviously return a non-empty string on `tag`, but this code also makes the assumption `getTag()` will always return an empty string on `push `and `pull request`. Do you know if that's a valid assumption?
> 
> I should have some time again next weekend to continue checking on this.

It would make sense because `this.getTag()` only gets a tag if it points at `HEAD`.

**Comment by webbertakken** [comment]
@davidmfinol could you check with unity-builder@b4bad43 ?

**Comment by davidmfinol** [comment]
@webbertakken Tried it out and got errors: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/112085957

I think `git describe --long --tags --always --debug v1.27.4` should be `git describe --long --tags --always --debug HEAD`

**Comment by webbertakken** [comment]
> @webbertakken Tried it out and got errors: https://github.com/finol-digital/Card-Game-Simulator/actions/runs/112085957
> 
> I think `git describe --long --tags --always --debug v1.27.4` should be `git describe --long --tags --always --debug HEAD`

That is odd, the documentation says it's looking for a `commit-ish` which the tag should be according to https://stackoverflow.com/questions/23303549/what-are-commit-ish-and-tree-ish-in-git.

I didn't go for HEAD because half the time it's detached so it's better to stay with the reference. Let me try headRef, which should do the same thing.

**Comment by webbertakken** [comment]
Thanks a lot to @davidmfinol for testing this a few times around. It's working now.

![image](https://user-images.githubusercontent.com/20756439/82709089-1e84fb80-9c80-11ea-868c-f3c0b15114b3.png)
