### ISSUE TITLE
Unity LTS

### ISSUE THREAD

**Issue by ZhouJiaZhi** [webbertakken/unity-actions#79]
Please provide a unity 2019 LTS version  for github action

**Comment by webbertakken** [comment]
Hi @ZhouJiaZhi 

Thank you for your request. 

You can use all unity LTS versions as far as I know. Not sure what you're asking exactly. Could you please elaborate?

**Comment by ZhouJiaZhi** [comment]
@webbertakken 
1. In your .github/workflow/main.yml I saw unity version is not unity2019 LTS
2. I think to upload my account and password to Github have safety risks
<img width="550" alt="Screen Shot 2020-07-26 at 9 09 26 AM" src="https://user-images.githubusercontent.com/20750357/88469095-bbce0b80-cf1f-11ea-81f8-d14357f8a5dc.png">

**Comment by ZhouJiaZhi** [comment]
@webbertakken 
And I want to maintain a unity-action copy in my own repo, could you provide some advice including but not limited to: 
1.deploy to docker
2.What configuration items do I need to modify in .*yml file at least

**Comment by ZhouJiaZhi** [comment]
@webbertakken 
I use personally licence, but I do not know  what is the value of **UNITY_LICENSE**, where could I find the value
<img width="545" alt="Screen Shot 2020-07-26 at 9 25 35 AM" src="https://user-images.githubusercontent.com/20750357/88469246-f9cc2f00-cf21-11ea-97d4-a5a1513885be.png">

**Comment by webbertakken** [comment]
Hi @ZhouJiaZhi, let me try to answer your questions;

> @webbertakken
> 
> 1. In your .github/workflow/main.yml I saw unity version is not unity2019 LTS
> 2. I think to upload my account and password to Github have safety risks
> 
> <img alt="Screen Shot 2020-07-26 at 9 09 26 AM" width="550" src="https://user-images.githubusercontent.com/20750357/88469095-bbce0b80-cf1f-11ea-81f8-d14357f8a5dc.png">

1. Correct, that workflow is just to test the action itself, you should refer to the [readme](https://unity-ci.com/docs/github/getting-started) to find out how to get started.
2. To use your account name or password in plain text has major security risks. This is what secrets are for, the output should always be masked by GitHub. The username and password are required to activate unity professional licenses and there is no way around this as far as I know.

> @webbertakken
> And I want to maintain a unity-action copy in my own repo, could you provide some advice including but not limited to:
> 1.deploy to docker
> 2.What configuration items do I need to modify in .*yml file at least

1. Note that this action never deploys anything to docker, instead the local docker image is used, based on the Dockerfile.
2. I made this action open source so that other people do not need to reinvent the wheel. The idea that this action covers all major use cases so that we can create a community that can help each other when actual problems occur. That said; Actions are always open source and you're free to create a fork of this project. All the code is provided under MIT license, feel free to take what you need, but I would recommend starting off with just making a clone. You can find all documentation on how to create and maintain an Action in GitHub's official [docs](https://docs.github.com/en/actions/creating-actions).

> @webbertakken
> I use personally licence, but I do not know what is the value of **UNITY_LICENSE**, where could I find the value
> <img alt="Screen Shot 2020-07-26 at 9 25 35 AM" width="545" src="https://user-images.githubusercontent.com/20750357/88469246-f9cc2f00-cf21-11ea-97d4-a5a1513885be.png">

You may refer to the Unity Actions [docs](https://unity-ci.com/docs/github/getting-started). It'll take you through the process of setting up your workflow.

**Comment by ZhouJiaZhi** [comment]
@webbertakken 
I used the method in the manual but failed , Do you know how to solve it
<img width="651" alt="Screen Shot 2020-07-27 at 7 51 54 PM" src="https://user-images.githubusercontent.com/20750357/88538844-a8679100-d042-11ea-8ea5-7d976d19137d.png">
<img width="1244" alt="Screen Shot 2020-07-27 at 7 50 36 PM" src="https://user-images.githubusercontent.com/20750357/88538847-abfb1800-d042-11ea-8fa2-b2b20e96c51d.png">
